### ISSUE TITLE
NativeClient: NaCl module crashed

### ISSUE THREAD

**Issue by cottonwool** [GoogleChromeLabs/chromeos_network_file_share#36]
Whilst accessing a file from an SMB share on a Fritz Box a pop-up appeared saying:

"An operation is taking longer than expected. Do you want to abort it?"

Checking  the log it looks like the NaCL module crashed.

The current operation was simply playing a file through the music player.

Is there a way to get more debug or other diagnostics?

The access denied message in the log was probably related to trying to open and use RO files.

NACL ERROR: Error performing openFile:smbc_open: errno=13 errtxt=Permission denied
log.js:68 ERROR: rejecting message 1716 ACCESS_DENIED
log.js:68 ERROR: openFile rejected promise
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1762 SHOULD_RETRY
log.js:68 WARNING: readFile[1762] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1762 SHOULD_RETRY
log.js:68 WARNING: readFile[1762] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1762 SHOULD_RETRY
log.js:68 ERROR: readFile[1762] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: readFile failed with FAILED
log.js:24 NACL ERROR: closeFile:smbc_close: Error closing fd
extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedSuccess: NOT_FOUND
    at .<anonymous> (chrome-extension://ndjpildffkeodjdaeebdhnncfhopkajk/samba.js:350:17)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1806 SHOULD_RETRY
log.js:68 WARNING: readFile[1806] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1806 SHOULD_RETRY
log.js:68 WARNING: readFile[1806] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1806 SHOULD_RETRY
log.js:68 ERROR: readFile[1806] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: readFile failed with FAILED
log.js:24 NACL ERROR: closeFile:smbc_close: Error closing fd
plugin.html:1 NativeClient: NaCl module crashed

**Comment by cottonwool** [comment]
With the app in this state I can't close the shares from within the Chrome OS filer or reattach.

It looks like I will have to reboot my Chromebook!!!!

**Comment by illiminable** [comment]
You should be able to go to chrome://extensions and disable then re-enable the app. That should tear it down without a reboot.

Currently you can't get more verbose logs unless you build it yourself. Could you tell me;
- the approximate size of the file
- is this on a possibly slow/spotty wifi connection
- If you know if your SMB device only support SMB v1

It might be a side effect of the RO thing. Maybe we can revisit after I resolve that one?

**Comment by cottonwool** [comment]
The files I was accessing are between 16MB and 32MB.

The connection is a WiFi network where the laptop is within arms reach of the 802.11n router. I believe it is as good as it gets.

I can use Wireshark to analyse the SMB transactions. The Fritz Box router can capture the traces so if I knew what to look for I could check see which version

~~This is not a high priority as it happens rarely and~~ This has happened a second time now, just as I was typing the comments, but  there is a work around to tear down the app and restart it.

NACL ERROR: closeFile:smbc_close: Error closing fd
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 425 SHOULD_RETRY
log.js:68 WARNING: readDirectory[425] failed on attempt 1 of 3. Retrying...
extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedSuccess: NOT_FOUND
    at .<anonymous> (chrome-extension://ndjpildffkeodjdaeebdhnncfhopkajk/samba.js:350:17)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1188 SHOULD_RETRY
log.js:68 WARNING: readFile[1188] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1188 SHOULD_RETRY
log.js:68 WARNING: readFile[1188] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readFile:smbc_read: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 1188 SHOULD_RETRY
log.js:68 ERROR: readFile[1188] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: readFile failed with FAILED
log.js:24 NACL ERROR: closeFile:smbc_close: Error closing fd
plugin.html:1 NativeClient: NaCl module crashed

**Comment by cottonwool** [comment]
Disabling then enabling the app worked to reset the app.

**Comment by illiminable** [comment]
Could you also tell me which Chromebook you have? The crash is new but "Software caused connection abort" has happened sporadically in the past, though I thought most issues of it had gone away. I haven't totally pinned down what conditions cause this but this is a pretty low level error from the OS but it seems related to the size of the read buffers.

Besides the crash it's the same as https://github.com/GoogleChrome/chromeos_network_file_share/issues/1

**Comment by cottonwool** [comment]
HP Chromebook 14 - q011sa

Intel 2995U, 4GB ram, 16GB storage

Version 50.0.2661.103 (64-bit)
Platform 7978.74.0 (Official Build) stable-channel falco
Firmware Google_Falco.4389.92.0

**Comment by antokara** [comment]
Using:
Toshiba Chromebook 2 - 2015 Edition (CB35-C3350)
Intel Core i3-5015U 2.1 GHz Processor
4 GB RAM / 16 GB Solid-State Drive

Connecting with credentials on a SMB share from Windows 10 and playing ~250MB .mkv files,
it freezes after about 30 minutes.

**chrome://restart**
resolves the issue or 
toggling the **Network File Share for Chrome OS** extension but this also disconnects the share (and loses the path / credentials)

I think I can reproduce it 100% of the times. 
Tried it so far with a couple of different files and it always happened around at the same time.

Checking the console, it has the **NativeClient: NaCl module crashed** but not much else information

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
