### ISSUE TITLE
"operations taking longer than expected"

### ISSUE THREAD

**Issue by liltinkerer** [GoogleChromeLabs/chromeos_network_file_share#49]
I understand that this is a Chrome OS limit, but it takes few minutes to actually see files.
The samba server works fine with other devices. It has only ~150 files to show, so it's not a huge amount.

It doesn't show any helpful errors or notifications to troubleshoot the problem. Sometimes only restart helps.

It would be nice if after unmount the application would remember your entered details.

ARM Asus C201 Chromebook.

`In common.js - DOMContentLoaded
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
plugin.html:1 Size specified, but not requested.
plugin.html:1 Last modification time specified, but not requested.
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 13 SHOULD_RETRY
log.js:68 WARNING: readDirectory[13] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 14 SHOULD_RETRY
log.js:68 WARNING: readDirectory[14] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 13 SHOULD_RETRY
log.js:68 WARNING: readDirectory[13] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 14 SHOULD_RETRY
log.js:68 WARNING: readDirectory[14] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 13 SHOULD_RETRY
log.js:68 ERROR: readDirectory[13] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: readDirectory failed with FAILED
plugin.html:1 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedError: NOT_FOUND
    at chrome-extension://ndjpildffkeodjdaeebdhnncfhopkajk/samba.js:643:13
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 15 SHOULD_RETRY
log.js:68 WARNING: readDirectory[15] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing readDirectory:smbc_opendir: errno=103 errtxt=Software caused connection abort
log.js:68 ERROR: rejecting message 14 SHOULD_RETRY
log.js:68 ERROR: readDirectory[14] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: readDirectory failed with FAILED
plugin.html:1 Unchecked runtime.lastError while running fileSystemProviderInternal.operationRequestedError: NOT_FOUND
    at chrome-extension://ndjpildffkeodjdaeebdhnncfhopkajk/samba.js:643:13
plugin.html:1 NativeClient: NaCl module crashed`

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
