### ISSUE TITLE
Network Share Fails to Mount in version 0.80.17230

### ISSUE THREAD

**Issue by mleong30** [GoogleChromeLabs/chromeos_network_file_share#90]
On a HP Chromebook (Chrome OS version 59.0.3071.134) updated to network_file_share version 0.80.17230, attempts to mount any network shares fails with the message "Share could not be mounted" after about 6 seconds of "Mounting network share ...". The same shares mounted successfully previously before system automatically updated from version 0.70.16144.

On a separate Samsung Chromebook (Chrome OS 59.0.3071.134) which is currently still on network_file_share version 0.70.16144 and is in the same network, there is no issue mounting the exact same shares using identical input parameters.

A screenshot of the Mount File Share dialog is attached.
![screenshot 2017-08-19 at 9 55 59 pm](https://user-images.githubusercontent.com/31172917/29491780-d69f513a-852b-11e7-8cfa-b232f5ecaf71.png)

**Comment by illiminable** [comment]
This is most likely because SMB1 was disabled in this release. See this link for additional information about why - https://blogs.technet.microsoft.com/filecab/2016/09/16/stop-using-smb1/

Could you please tell us what NAS device (make/model if you know and approximately how old it is) or OS (if it's a desktop with a share) you are having trouble connecting to. 

We'd like to find out the prevalence of devices that only support SMB1. In some cases there may be configuration or updates that could be applied to the device to enable SMB2.

**Comment by illiminable** [comment]
Also to rule out a problem with name resolution. Please try to connect to the device by IP address and let us know if that works.

**Comment by miguelcandian** [comment]
I have the same issue. I have a LaCie d2 Network 2 running firmware version 2.2.12.2. It stopped working with the latest update.

**Comment by hughnguyen82** [comment]
I have had the same issue, using Samsung Chromebook Pro, connecting to Buffalo NAS LS-QVL, firmware version 1.73

I rooted the NAS, ssh-ed in and checked the Samba version, found 3.6.3, and it was indeed only configured to run SMB1

So I upgraded to samba 3.6.23, enabled SMB2 in smb.conf.

I verified that SMB2 was working, by accessing the shares using Windows, and run Powershell command: get-smbconnection. The output showed the smb dialect  2.0.2, indicating that SMB2 was indeed working.

I tried to access from the Chromebook again, and get the same error.

The chrome extension console showed these:

NACL ERROR: Error performing mount:smb_opendir: errno=110 errtxt=Connection timed out

The error was the same as before I enabled SMB2

**Comment by illiminable** [comment]
@hughnguyen82 Can you confirm that it also does not work when you try to connect using the IP address?

**Comment by hughnguyen82** [comment]
yes, I used ip address to connect.

I tried with both format: \\123.123.123.123\share_name and smb://123.123.123.123/share_name

I changed log level in smb.conf to 3, and get this log on the NAS whenever the chromebook tries to connect: (I masked away the chromebook's IP with 123.123.123.111)

`[2017/09/01 14:57:57.041340,  3] lib/access.c:338(allow_access)
  Allowed connection from 123.123.123.111 (123.123.123.111)
[2017/09/01 14:57:57.041815,  3] smbd/oplock.c:922(init_oplocks)
  init_oplocks: initializing messages.
[2017/09/01 14:57:57.042332,  3] smbd/oplock_linux.c:246(linux_init_kernel_oplocks)
  Linux kernel oplocks enabled
[2017/09/01 14:57:57.044754,  3] smbd/process.c:1662(process_smb)
  Transaction 0 of length 112 (0 toread)
[2017/09/01 14:57:57.047276,  2] smbd/smb2_server.c:2557(smbd_smb2_request_incoming)
  smbd_smb2_request_incoming: client read error NT_STATUS_PIPE_BROKEN
[2017/09/01 14:57:57.047843,  3] smbd/server_exit.c:180(exit_server_common)
  Server exit (NT_STATUS_PIPE_BROKEN)
`

**Comment by Kaablume** [comment]
I am experiencing the same issue with enterprise file shares hosted on Win server 2008 R2.  SMB 2/3 are enabled but the shares are still unable to mount.  SMB 1 is still enabled as well.  I have attempted to connect via DNS name and IP address with the same result.  Does SMB1 have to be disabled, after August's update, to mount the shares successfully?

**Comment by t0rv1c** [comment]
Same here

**Comment by hughnguyen82** [comment]
Just to update:
I installed Debian to my NAS box, install Samba to 4.5.8, and then everything works fine.

So I guess the issue is just incompatibility with old Samba 3.6.x, and the Google team couldn't spend their time to support it anymore.

**Comment by tawalker** [comment]
I found this thread whilst Googling for advice, on why my Chromebook Flip can't mount the SMB share on my travel router (HooToo TripMate Mini), using Network File Share.

I was puzzled at this, as I thought I'd entered all the details correctly - after all, my iPhone was able to access the same share via the [FileBrowser](https://www.stratospherix.com/products/filebrowser/) app, using the same info. Some detective-work later, and I pieced together the answer: the TripMate's SMB server uses SMB1 (which FileBrowser supports---FB also points out onscreen, when an SMB mount is based on SMB1).

As it looks like HooToo has discontinued the TripMate Mini, I doubt they'll update the firmware to change the SMB server to support SMB2. I'm looking for any alternative firmwares for the TripMate that might fix the problem, but I thought I'd post this in case any other TripMate owners are having the same problem with this.

**Comment by ricardoch1** [comment]
Hello,
Maybe a little outdated, 
I found that "File System for Windows" extension works fine with my old SMBv1 NAS. just a little "tricky" to connect at first trying to give all required details..., it's easier, just give IP and let it find everything else. (and weights a lot less)
I hope this helps
Happy new year

**Comment by illiminable** [comment]
Please note that SMB1 is not supported, but otherwise please try the new native support in Chrome OS.

Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
