### ISSUE TITLE
Change display name of share to distinguish from other shares to same server

### ISSUE THREAD

**Issue by schultzter** [GoogleChromeLabs/chromeos_network_file_share#96]
Good afternoon.

I have a NAS with four shares that I use regularly, but each one is mounted with the same display name in the Files App so I can't distinguish them!

Either the leaf directory should be used as the display name for the share in the Files app or we should be able to specify our own display name (preferably). 

Thanks,

**Comment by allenktv** [comment]
Hi Schultzter,

What version of the app are you using? In the latest version "0.80.17230", we have an optional field called "Display Name" where you can input your desired display name for the share._

**Comment by schultzter** [comment]
Sorry, you're right, I should have double-checked that.

However I can't connect to my NAS because of the v1 vs v2 issue. It would be nice if there was a way to accept v1 connections. 

Thanks,

**Comment by illiminable** [comment]
This is resolved. Also note that this functionality is now built natively into Chrome OS.

On Chrome 71 or higher you can.

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"
A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. The new implementation is an order magnitude or two faster and much more reliable.

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
